name: Userspace Build
on:
  workflow_dispatch:
  push:
    paths:
      - 'keyboards/**'
      - 'keymaps/*'
      - '.github/workflows/*'
      - '*.def'
      - '*.c'
      - '*.h'


jobs:
  list-user-keymaps:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ env.QMK_USER }}

      - id: set-matrix
        run: echo "matrix=$(ls keymaps/*.json | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  compile-userpace-keymaps:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    needs: list-user-keymaps
    strategy:
      fail-fast: false
      matrix:
        keymaps: ${{ fromJson(needs.list-user-keymaps.outputs.matrix) }}
    env:
      USERSPACE_PATH: users/${{ github.actor }}

    # by default, checks out to github.workspace
    # github.workspace will also be qmk_firmware root
    steps:
    - name: Checkout QMK
      uses: actions/checkout@v3.5.3
      with:
        repository: qmk/qmk_firmware
        ref: master
        submodules: true

    # path is relative to github.workspace
    - name: Checkout userspace
      uses: actions/checkout@v3.5.3
      with:
        path: ${{ env.USERSPACE_PATH }}
        persist-credentials: false

    - name: Setup safe directory
      run: git config --global --add safe.directory '*'

    - name: Install rsync
      run:  apt-get update; apt-get install -y rsync

    - name: Copy users/keyboards/* to keyboards/*
      run: rsync -av ${{ env.USERSPACE_PATH }}/keyboards/ keyboards/

    - name: QMK compile
      run: qmk compile -j 3 ${{ env.USERSPACE_PATH }}/${{ matrix.keymaps }}

    - name: Archive firmware
      uses: actions/upload-artifact@v3.1.2
      with:
        retention-days: 60
        name: qmk_firmware
        path: |
          *.hex
          *.bin
          *.uf2
